'use strict';

const {
  HEADER_NAME,
  internalNestorInferenceHeaders,
  trustedNestorConsumer,
} = require('../../src/services/nestorConsumerAttribution');

describe('Nestor consumer attribution', () => {
  it('accepts only the process-private header generated by the versioned service', () => {
    const headers = internalNestorInferenceHeaders();
    const req = { get: (name) => headers[String(name).toLowerCase()] };

    expect(trustedNestorConsumer(req)).toBe('nestor-v1');
    expect(trustedNestorConsumer({ get: () => 'spoofed' })).toBeNull();
    expect(trustedNestorConsumer({ get: () => 'é'.repeat(64) })).toBeNull();
    expect(trustedNestorConsumer({ get: () => '' })).toBeNull();
    expect(headers[HEADER_NAME]).toHaveLength(64);
  });
});
